import Card from "@/common/card";
// Data
import TsabeehData from "../../data/Tsabeh.json";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "الكلام الطيب | التسابيح",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className="py-1">
      <h1 className="flex justify-center items-center pt-7 text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-green_degree">
        التسابيح
      </h1>
      <div className="container mx-auto min-h-[80vh]">
        <div className="mx-5">
          {TsabeehData.map((ele, indx) => {
            return (
              <Card
                key={indx}
                type=""
                status={`تسبيح`}
                content={`${ele.Tsbeh}`}
                Info={ele.Info}
                count={ele.count}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default page;
