import Card from "@/common/card";
// Data
import DuaaData from "../../../data/Duaa.json";
import type { Metadata } from "next";
// Context Types
import { ContextType } from "@/types/context";

export const metadata: Metadata = {
  title: "الكلام الطيب | ادعيه من السنه",
  description: "Generated by create next app",
};

const page = (context: ContextType) => {
  return (
    <div className="py-1">
      <h1 className="flex justify-center items-center pt-7 text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-green_degree">
        {context.searchParams.category}
      </h1>
      <div className="container mx-auto min-h-[80vh]">
        <div className="mx-5">
          {DuaaData.map((ele, indx) => {
            if (ele.title === "Sunnah_Duaa") {
              return ele.content.map((D, indx) => {
                return (
                  <Card
                    key={indx}
                    type={`${D.type}`}
                    status={`${D.type}`}
                    content={`${D.Duaa}`}
                    Info={D.Info}
                    count={1}
                  />
                );
              });
            }
          })}
        </div>
      </div>
    </div>
  );
};

export default page;
