import "./general.css";
import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";
import UpBtn from "@/common/upBtn";

export const metadata: Metadata = {
  title: "الكلام الطيب | الرئيسيه",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="https://raw.githubusercontent.com/DATA-Container-100/hotel-cdn-imgs/main/uploads/Pray.svg"
          type="image/x-icon"
        />
        <link
          rel="preload"
          href="https://raw.githubusercontent.com/DATA-Container-100/hotel-cdn-imgs/main/uploads/bg_small.png"
          as="image"
        />
      </head>
      <body>
        <Header />
        <div
          style={{
            backgroundImage:
              "url('https://raw.githubusercontent.com/DATA-Container-100/hotel-cdn-imgs/main/uploads/bg_small.png')",
          }}
        >
          {children}
        </div>
        <UpBtn />
        <Footer />
      </body>
    </html>
  );
}
