import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "الكلام الطيب | اذكار",
  description: "Generated by create next app",
};

const page = () => {
  const nav = [
    {
      title: "اذكار الصباح",
      img: "https://raw.githubusercontent.com/DATA-Container-100/hotel-cdn-imgs/main/uploads/SabahZikr.svg",
      path: "/Zikr/SabahZikr",
    },
    {
      title: "أذكار المساء",
      img: "https://raw.githubusercontent.com/DATA-Container-100/hotel-cdn-imgs/main/uploads/MassaZikr.svg",
      path: "/Zikr/MassaZikr",
    },
    {
      title: "أذكار بعد الصلاه",
      img: "https://raw.githubusercontent.com/DATA-Container-100/hotel-cdn-imgs/main/uploads/AfterPrayZikr.svg",
      path: "/Zikr/AfterPrayZikr",
    },
  ];
  return (
    <div className="container mx-auto min-h-[80vh] flex flex-col justify-center items-center">
      <h1 className="text-center my-10 sm:mt-0 text-4xl sm:text-5xl text-green_degree font-bold">
        اذكار المسلم
      </h1>
      <div className="flex flex-col sm:flex-row-reverse justify-center items-center">
        {nav.map((link, indx) => {
          return (
            <Link
              href={{
                pathname: `${link.path}`,
                query: {
                  category: `${link.title}`,
                },
              }}
              key={indx}
              className="mb-5 sm:mb-0 sm:mx-2 md:mx-3 lg:mx-5 border-2 border-green_degree p-5 rounded-md"
            >
              <div className="flex flex-col justify-center items-center">
                <Image
                  src={link.img}
                  width={200}
                  height={200}
                  alt=""
                  className="w-[200px] h-[200px] sm:w-[250px] sm:h-[250px] md:w-[300px] md:h-[300px]"
                  priority={true}
                />
                <h4 className="text-xl font-bold text-text_color">
                  {link.title}
                </h4>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
};

export default page;
