import Card from "@/common/card";
// Data
import ZikrData from "../../../data/Zikr.json";
import type { Metadata } from "next";
// Context Types
import { ContextType } from "@/types/context";

export const metadata: Metadata = {
  title: "الكلام الطيب | اذكار المساء",
  description: "Generated by create next app",
};

const page = (context: ContextType) => {
  return (
    <div className="py-1">
      <h1 className="flex justify-center items-center pt-7 text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-green_degree">
        {context.searchParams.category}
      </h1>
      <div className="container mx-auto min-h-[80vh]">
        <div className="mx-5">
          {ZikrData.map((ele, indx) => {
            if (ele.title === "Masaa_Zikr") {
              return ele.content.map((z, indx) => {
                return (
                  <Card
                    key={indx}
                    type={`${z.type}`}
                    status={`ذكر`}
                    content={`${z.zikr}`}
                    Info={z.Info}
                    count={z.count}
                  />
                );
              });
            }
          })}
        </div>
      </div>
    </div>
  );
};

export default page;
